/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * File Name          : STM32TouchController.cpp
  ******************************************************************************
  * This file is generated by TouchGFX Generator 4.20.0.
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2023 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */
/* USER CODE END Header */

/* USER CODE BEGIN STM32TouchController */

#include <STM32TouchController.hpp>

#ifdef FT5206_TOUCH_DRIVER
#include "ft5206.h"
#else
#include "gt9147.h"
#endif

#include "cmsis_os.h"

extern osMessageQueueId_t touch_posQueueHandle;

void STM32TouchController::init()
{
    /**
     * Initialize touch controller and driver
     *
     */
	GPIO_InitTypeDef GPIO_Initure;
	__HAL_RCC_GPIOB_CLK_ENABLE();           //开启GPIOB时钟

	GPIO_Initure.Pin=GPIO_PIN_0|GPIO_PIN_1; //PB1,0
	GPIO_Initure.Mode=GPIO_MODE_OUTPUT_PP;  //推挽输出
	GPIO_Initure.Pull=GPIO_PULLUP;          //上拉
	GPIO_Initure.Speed=GPIO_SPEED_HIGH;     //高速
	HAL_GPIO_Init(GPIOB,&GPIO_Initure);

	HAL_GPIO_WritePin(GPIOB,GPIO_PIN_0,GPIO_PIN_SET);	//PB0置1 
	HAL_GPIO_WritePin(GPIOB,GPIO_PIN_1,GPIO_PIN_SET);	//PB1置1 
	
#ifdef FT5206_TOUCH_DRIVER
	while(FT5206_Init());
#else
	while(GT9147_Init());
#endif
}
#define the_x 0
#define the_y 1
bool STM32TouchController::sampleTouch(int32_t& x, int32_t& y)
{
    /**
     * By default sampleTouch returns false,
     * return true if a touch has been detected, otherwise false.
     *
     * Coordinates are passed to the caller by reference by x and y.
     *
     * This function is called by the TouchGFX framework.
     * By default sampleTouch is called every tick, this can be adjusted by HAL::setTouchSampleRate(int8_t);
     *
     */
//	uint16_t tt_x,tt_y;
//#ifdef FT5206_TOUCH_DRIVER
//	if(get_touch(&tt_x,&tt_y)==1)
//	{
//#else
//	if(gt_get_touch(&tt_x,&tt_y)==1)
//	{
//#endif
//		x=tt_x;
//		y=tt_y;
	union t_pos
	{
		uint32_t data;
		uint16_t buf[2];
	}t_pos;
	if(osMessageQueueGetCount(touch_posQueueHandle)!=0)
	{
		osMessageQueueGet(touch_posQueueHandle, &t_pos.data, (uint8_t *)1, 50);
		x=t_pos.buf[the_x];
		y=t_pos.buf[the_y];
		PBout(1)=0;
		return true;
	}
		
	else{
		x=-1;
		y=-1;
		PBout(1)=1;
		return false;
	}
}

/* USER CODE END STM32TouchController */

/************************ (C) COPYRIGHT STMicroelectronics *****END OF FILE****/
